# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cedri\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\muenster_city_district_tools\export.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 403)
        self.pbExportPdf = QtWidgets.QPushButton(Dialog)
        self.pbExportPdf.setGeometry(QtCore.QRect(10, 20, 271, 61))
        self.pbExportPdf.setObjectName("pbExportPdf")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(14, 95, 531, 51))
        self.label.setObjectName("label")
        self.pbExportCsv = QtWidgets.QPushButton(Dialog)
        self.pbExportCsv.setGeometry(QtCore.QRect(10, 200, 271, 61))
        self.pbExportCsv.setObjectName("pbExportCsv")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 531, 51))
        self.label_2.setObjectName("label_2")
        self.pbOk = QtWidgets.QPushButton(Dialog)
        self.pbOk.setGeometry(QtCore.QRect(200, 350, 151, 28))
        self.pbOk.setObjectName("pbOk")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pbExportPdf.setText(_translate("Dialog", "Export als *.pdf"))
        self.label.setText(_translate("Dialog", "Die Werte des selektierten Feauters werden in einen *.pdf-Steckbrief geschrieben.\n"
"Bitte geben Sie hierzu noch einen Ausgabepfad an. Bitte beachten Sie, dass nur ein\n"
"Feature ausgewählt ist."))
        self.pbExportCsv.setText(_translate("Dialog", "Export als *.csv"))
        self.label_2.setText(_translate("Dialog", "Die Werte der selektierten Feature werden in einen *.csv exportiert. Bitte \n"
"geben Sie hierzu noch einen Ausgabepfad an."))
        self.pbOk.setText(_translate("Dialog", "Ok"))
