# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MuensterCityDistrictToolsDialog
                                 A QGIS plugin
 Muenster City District Tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-17
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Gräber_Große_Beikel
        email                : cedric.graeber@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import QgsProject

from .statistics import Statistics
from .profile import Ui_Dialog
from .export import Ui_Dialog as Ui_ExportDialog
from .pdf_creation import create_pdf_profile

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'muenster_city_district_tools_dialog_base.ui'))


class MuensterCityDistrictToolsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None): # runs ONCE when the window opens
        super(MuensterCityDistrictToolsDialog, self).__init__(parent)
        self.setupUi(self) # buttons now exist in code
        self.pbQuery.clicked.connect(self.open_query_dialog) # wiring — INSIDE __init__
        self.pbExport.clicked.connect(self.open_export_dialog)# wiring — INSIDE __init__
    def open_query_dialog(self): 
        try:
            # 1. ERZWINGE DIE INITIALISIERUNG HIER (Behebt den 'no attribute stats' Fehler)
            if not hasattr(self, 'stats') or self.stats is None:
                self.stats = Statistics()

            # 2. Greife auf den Stadtbezirke-Layer in QGIS zu
            layer_list = QgsProject.instance().mapLayersByName("Muenster_City_Districts")
            
            # ABSICHERUNG: Falls die Liste leer ist -> 'list index out of range' verhindern
            if not layer_list or len(layer_list) == 0:
                QMessageBox.critical(
                    self, 
                    "Layer nicht gefunden", 
                    "Der Layer 'Muenster_City_Districts' wurde in QGIS nicht gefunden!\n\n"
                    "Bitte überprüfe, ob der Layer in deiner QGIS-Layer-Liste exakt so heißt."
                )
                return
                
            layer = layer_list[0]
            features = layer.selectedFeatures() # Holt alle blau markierten Features

            # 3. Validierungs-Regeln prüfen
            if len(features) == 0:
                QMessageBox.warning(self, "Auswahl fehlt", "Bitte wählen Sie mindestens einen Stadtbezirk auf der Karte aus.")
                return
            
            if len(features) > 1:
                QMessageBox.warning(self, "Zu viele Features", "Es kann nur ein Stadtbezirk gleichzeitig abgefragt werden.")
                return

            # Wenn wir hier ankommen, ist exakt 1 Bezirk ausgewählt
            district_feature = features[0]

            # 4. Berechne die Daten mit deiner "build_profile_dict"-Methode
            # HINWEIS: Wenn der Fehler 'list index out of range' HIER drin passiert,
            # liegt es an einem der Layer in der statistics.py!
            profile_data = self.stats.build_profile_dict(district_feature)

            # --- FENSTER ÖFFNEN & BEFÜLLEN ---
            dialog = QtWidgets.QDialog(self) 
            ui = Ui_Dialog() 
            ui.setupUi(dialog) 
            
            # Setze den Fenstertitel mit dem Namen des Bezirks
            dialog.setWindowTitle(f"Profil von {profile_data['name']}")
            
            # Befülle das Textfeld im Profil-Fenster mit den echten Variablen
            ui.profileText.setText(
                f"Stadtbezirk: {profile_data['name']}\n"
                f"Übergeordneter Bezirk: {profile_data['parent']}\n"
                f"Größe: {profile_data['area']} km²\n"
                f"Haushalte: {profile_data['households']}\n"
                f"Flurstücke (Parcels): {profile_data['parcels']}\n"
                f"Schulen: {profile_data['schools']}\n"
                f"Schwimmbäder: {profile_data['pools']}"
            )
            
            ui.pbClose.clicked.connect(dialog.close) 
            dialog.exec_() # Zeigt das berechnete Profil-Fenster an

        except Exception as e:
            QMessageBox.critical(self, "Fehler", f"Ein Fehler ist aufgetreten:\n{str(e)}")
    def open_export_dialog(self):
        """Öffnet das Export-Auswahlfenster (CSV / PDF)."""
        try:
            # Hole den Layer, um die Selektion vorab zu prüfen 
            layer_list = QgsProject.instance().mapLayersByName("Muenster_City_Districts")
            if not layer_list:
                QMessageBox.critical(self, "Fehler", "Der Layer 'Muenster_City_Districts' wurde nicht gefunden! [cite: 313]")
                return
            
            layer = layer_list[0]
            features = layer.selectedFeatures() 

            # Validierung: Für jeden Export muss mindestens 1 Feature selektiert sein! [cite: 260, 322]
            if len(features) == 0:
                QMessageBox.warning(self, "Auswahl fehlt", "Bitte wählen Sie mindestens einen Stadtbezirk auf der Karte aus[cite: 154].")
                return

            # Erstelle das Export-Fenster [cite: 252]
            dialog = QtWidgets.QDialog(self)
            ui = Ui_ExportDialog()
            ui.setupUi(dialog)
            
            # Verkabelung der Buttons mittels lambda-Funktionen 
            # Stelle sicher, dass die objectNames (pbExportCsv, pbExportPdf, pbOk) exakt mit Qt Designer übereinstimmen! [cite: 69, 73]
            ui.pbExportCsv.clicked.connect(lambda: self.export_csv(features))
            ui.pbExportPdf.clicked.connect(lambda: self.export_pdf(features))
            ui.pbOk.clicked.connect(dialog.close) 
            
            dialog.exec_() 

        except Exception as e:
            QMessageBox.critical(self, "Fehler", f"Fehler beim Öffnen des Export-Dialogs:\n{str(e)} ")
    def export_csv(self, features):
        """Exportiert die ausgewählten Bezirke in eine CSV-Datei."""
        # 1. Datei-Speichern-Dialog öffnen 
        options = QtWidgets.QFileDialog.Options() 
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self, "CSV exportieren", "", "CSV Files (*.csv)", options=options 
        )
        
        # 2. Wenn abgebrochen wurde 
        if not path:
            QMessageBox.information(self, "Abgebrochen", "Der CSV-Export wurde abgebrochen.")
            return

        try:
            # Sicherstellen, dass die Engine bereit ist 
            if not hasattr(self, 'stats') or self.stats is None:
                self.stats = Statistics()

            # 3. CSV-Inhalt generieren 
            # Header laut Vorgabe 
            lines = ["district_name;size_km2;number_parcels;number_schools"] 
            
            for f in features:
                name = f["Name"]
                area = self.stats.get_area_km2(f) 
                parcels = self.stats.count_parcels(f) 
                schools = self.stats.count_schools(f) 
                
                lines.append(f"{name};{area};{parcels};{schools}") 
            
            # UTF-8 schreiben, um Umlaute wie 'Münster-Mitte' zu erhalten
            with open(path, "w", encoding="utf-8") as file:
                file.write("\n".join(lines)) 
                
            QMessageBox.information(self, "Erfolg", "CSV-Datei wurde erfolgreich erstellt! ") 

        except Exception as e:
            QMessageBox.critical(self, "Fehler", f"Fehler beim Schreiben der CSV:\n{str(e)} ")
    def export_pdf(self, features):
        """Überprüft die Single-Feature-Regel für das PDF und exportiert das Profil."""
        # Kriterium laut Leitfaden: PDF-Reports gehen nur für exakt ein ausgewähltes Element!
        if len(features) != 1:
            QMessageBox.warning(
                self, "Auswahl ungültig", 
                "Ein PDF-Profil kann nur für exakt einen Stadtbezirk gleichzeitig erstellt werden."
            )
            return

        options = QtWidgets.QFileDialog.Options()
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self, "PDF exportieren", "", "PDF Files (*.pdf)", options=options
        )
        
        if not path:
            QMessageBox.information(self, "Abgebrochen", "Der PDF-Export wurde abgebrochen.")
            return

        try:
            # Ruft dein separates pdf_creation-Modul auf
            create_pdf_profile(features[0], path)
            QMessageBox.information(self, "Erfolg", "PDF-Profil wurde erfolgreich exportiert!")
            
        except Exception as e:
            QMessageBox.critical(self, "Fehler", f"Fehler bei der PDF-Erstellung:\n{str(e)}")