# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cedri\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\muenster_city_district_tools\profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 403)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 531, 401))
        self.groupBox.setObjectName("groupBox")
        self.profileText = QtWidgets.QLabel(self.groupBox)
        self.profileText.setGeometry(QtCore.QRect(4, 120, 521, 141))
        self.profileText.setWordWrap(True)
        self.profileText.setObjectName("profileText")
        self.pbClose = QtWidgets.QPushButton(self.groupBox)
        self.pbClose.setGeometry(QtCore.QRect(410, 350, 93, 28))
        self.pbClose.setObjectName("pbClose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.profileText.setText(_translate("Dialog", "TextLabel"))
        self.pbClose.setText(_translate("Dialog", "Close"))
